using System.Collections.Generic;

namespace TripleTriad
{
    static public class Cards
    {
        public enum CardTypes
        {
            NoType, Beast, Scion, Garlean, Primal
        };

        public struct CardStruct
        {
            public int Rarity;          // Rarity 1 to 5
            public int[] Power;         // Card Power (from 12 o'clock, clockwise)
            public CardTypes CardType;  // Type of card
        }

        static public IReadOnlyDictionary<string, CardStruct> En = new Dictionary<string, CardStruct>()
        {
            { "", new CardStruct { Rarity = 0, Power = new int[] { 0, 0, 0, 0 } } },        // Empty Card
            { "Bomb", new CardStruct { Rarity = 1, Power = new int[] { 3, 4, 3, 3 } } },
            { "Coeurl", new CardStruct { Rarity = 1, Power = new int[] { 2, 5, 2, 5 } } },
            { "Dodo", new CardStruct { Rarity = 1, Power = new int[] { 4, 2, 3, 4 } } },
            { "Mandragora", new CardStruct { Rarity = 1, Power = new int[] { 4, 2, 5, 3 } } },
            { "Sabotender", new CardStruct { Rarity = 1, Power = new int[] { 4, 3, 3, 3 } } },
            { "Ahriman", new CardStruct { Rarity = 1, Power = new int[] { 5, 5, 2, 2 } } },
            { "Amalj'aa", new CardStruct { Rarity = 1, Power = new int[] { 1, 4, 7, 1 }, CardType = CardTypes.Beast } },
            { "Chocobo", new CardStruct { Rarity = 1, Power = new int[] { 3, 7, 2, 1 } } },
            { "Coblyn", new CardStruct { Rarity = 1, Power = new int[] { 3, 3, 3, 4 } } },
            { "Goobbue", new CardStruct { Rarity = 1, Power = new int[] { 2, 5, 5, 2 } } },
            { "Ixal", new CardStruct { Rarity = 1, Power = new int[] { 6, 1, 3, 4 }, CardType = CardTypes.Beast } },
            { "Kobold", new CardStruct { Rarity = 1, Power = new int[] { 2, 2, 4, 6 }, CardType = CardTypes.Beast } },
            { "Moogle", new CardStruct { Rarity = 1, Power = new int[] { 2, 1, 3, 7 } } },
            { "Morbol", new CardStruct { Rarity = 1, Power = new int[] { 5, 2, 5, 2 } } },
            { "Pudding", new CardStruct { Rarity = 1, Power = new int[] { 2, 4, 3, 5 } } },
            { "Sahagin", new CardStruct { Rarity = 1, Power = new int[] { 4, 5, 3, 3 }, CardType = CardTypes.Beast } },
            { "Spriggan", new CardStruct { Rarity = 1, Power = new int[] { 2, 3, 4, 4 } } },
            { "Sylph", new CardStruct { Rarity = 1, Power = new int[] { 2, 4, 5, 4 }, CardType = CardTypes.Beast } },
            { "Tataru Taru", new CardStruct { Rarity = 1, Power = new int[] { 7, 2, 3, 2 }, CardType = CardTypes.Scion } },
            { "Tonberry", new CardStruct { Rarity = 1, Power = new int[] { 2, 2, 7, 2 } } },
            { "Baderon Tenfingers", new CardStruct { Rarity = 2, Power = new int[] { 3, 7, 5, 5 } } },
            { "Biggs & Wedge", new CardStruct { Rarity = 2, Power = new int[] { 5, 3, 7, 5 } } },
            { "Blue Dragon", new CardStruct { Rarity = 2, Power = new int[] { 2, 2, 7, 7 } } },
            { "Chimera", new CardStruct { Rarity = 2, Power = new int[] { 7, 7, 2, 2 } } },
            { "Demon Wall", new CardStruct { Rarity = 2, Power = new int[] { 6, 7, 2, 3 } } },
            { "Frixio", new CardStruct { Rarity = 2, Power = new int[] { 6, 2, 6, 6 }, CardType = CardTypes.Beast } },
            { "Gerolt", new CardStruct { Rarity = 2, Power = new int[] { 1, 7, 3, 7 } } },
            { "Livia sas Junius", new CardStruct { Rarity = 2, Power = new int[] { 3, 7, 7, 1 }, CardType = CardTypes.Garlean } },
            { "Memeroon", new CardStruct { Rarity = 2, Power = new int[] { 6, 6, 6, 2 }, CardType = CardTypes.Beast } },
            { "Momodi Modi", new CardStruct { Rarity = 2, Power = new int[] { 7, 5, 5, 3 } } },
            { "Mother Miounne", new CardStruct { Rarity = 2, Power = new int[] { 5, 5, 3, 7 } } },
            { "Mutamix Bubblypots", new CardStruct { Rarity = 2, Power = new int[] { 2, 6, 6, 6 }, CardType = CardTypes.Beast } },
            { "Rhitahtyn sas Arvina", new CardStruct { Rarity = 2, Power = new int[] { 7, 1, 3, 7 }, CardType = CardTypes.Garlean } },
            { "Scarface Bugaal Ja", new CardStruct { Rarity = 2, Power = new int[] { 6, 6, 2, 6 }, CardType = CardTypes.Beast } },
            { "Siren", new CardStruct { Rarity = 2, Power = new int[] { 3, 6, 7, 2 } } },
            { "Succubus", new CardStruct { Rarity = 2, Power = new int[] { 7, 3, 2, 6 } } },
            { "Ultros & Typhon", new CardStruct { Rarity = 2, Power = new int[] { 2, 3, 6, 7 } } },
            { "Behemoth", new CardStruct { Rarity = 3, Power = new int[] { 7, 8, 4, 2 } } },
            { "Garuda", new CardStruct { Rarity = 3, Power = new int[] { 6, 1, 7, 7 }, CardType = CardTypes.Primal } },
            { "Gilgamesh & Enkidu", new CardStruct { Rarity = 3, Power = new int[] { 8, 3, 7, 3 } } },
            { "Godbert Manderville", new CardStruct { Rarity = 3, Power = new int[] { 6, 6, 5, 6 } } },
            { "Good King Moggle Mog XIII", new CardStruct { Rarity = 3, Power = new int[] { 7, 6, 7, 1 }, CardType = CardTypes.Primal } },
            { "Ifrit", new CardStruct { Rarity = 3, Power = new int[] { 7, 1, 6, 7 }, CardType = CardTypes.Primal } },
            { "Nero tol Scaeva", new CardStruct { Rarity = 3, Power = new int[] { 4, 1, 8, 7 }, CardType = CardTypes.Garlean } },
            { "Papalymo & Yda", new CardStruct { Rarity = 3, Power = new int[] { 3, 7, 8, 2 }, CardType = CardTypes.Scion } },
            { "Raya-O-Senna & A-Ruhn-Senna", new CardStruct { Rarity = 3, Power = new int[] { 5, 6, 6, 6 } } },
            { "Thancred", new CardStruct { Rarity = 3, Power = new int[] { 2, 3, 8, 7 }, CardType = CardTypes.Scion } },
            { "Titan", new CardStruct { Rarity = 3, Power = new int[] { 1, 7, 7, 6 }, CardType = CardTypes.Primal } },
            { "Urianger", new CardStruct { Rarity = 3, Power = new int[] { 8, 1, 4, 7 }, CardType = CardTypes.Scion } },
            { "Y'shtola", new CardStruct { Rarity = 3, Power = new int[] { 7, 8, 1, 4 }, CardType = CardTypes.Scion } },
            { "Alphinaud & Alisaie", new CardStruct { Rarity = 4, Power = new int[] { 9, 3, 3, 9 }, CardType = CardTypes.Scion } },
            { "Cid Garlond", new CardStruct { Rarity = 4, Power = new int[] { 5, 9, 9, 2 } } },
            { "Lahabrea", new CardStruct { Rarity = 4, Power = new int[] { 4, 9, 4, 8 } } },
            { "Leviathan", new CardStruct { Rarity = 4, Power = new int[] { 8, 8, 8, 1 }, CardType = CardTypes.Primal } },
            { "Louisoix Leveilleur", new CardStruct { Rarity = 4, Power = new int[] { 9, 4, 9, 3 }, CardType = CardTypes.Scion } },
            { "Minfilia", new CardStruct { Rarity = 4, Power = new int[] { 9, 8, 3, 5 }, CardType = CardTypes.Scion } },
            { "Odin", new CardStruct { Rarity = 4, Power = new int[] { 8, 8, 1, 8 }, CardType = CardTypes.Primal } },
            { "Ramuh", new CardStruct { Rarity = 4, Power = new int[] { 8, 1, 8, 8 }, CardType = CardTypes.Primal } },
            { "Shiva", new CardStruct { Rarity = 4, Power = new int[] { 1, 8, 8, 8 }, CardType = CardTypes.Primal } },
            { "Ultima Weapon", new CardStruct { Rarity = 4, Power = new int[] { 7, 8, 9, 1 }, CardType = CardTypes.Garlean } },
            { "Bahamut", new CardStruct { Rarity = 5, Power = new int[] { 9, 5, 9, 6 }, CardType = CardTypes.Primal } },
            { "Bartz Klauser", new CardStruct { Rarity = 5, Power = new int[] { 4, 4, 0xA, 0xA } } },
            { "Cloud Strife", new CardStruct { Rarity = 5, Power = new int[] { 9, 3, 9, 8 } } },
            { "Gaius van Baelsar", new CardStruct { Rarity = 5, Power = new int[] { 4, 0xA, 5, 9 }, CardType = CardTypes.Garlean } },
            { "Hildibrand & Nashu Mhakaracca", new CardStruct { Rarity = 5, Power = new int[] { 1, 8, 0xA, 8 } } },
            { "Kan-E-Senna", new CardStruct { Rarity = 5, Power = new int[] { 9, 0xA, 1, 7 } } },
            { "Merlwyb Bloefhiswyn", new CardStruct { Rarity = 5, Power = new int[] { 5, 9, 0xA, 3 } } },
            { "Nanamo Ul Namo", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 6, 4, 8 } } },
            { "Onion Knight", new CardStruct { Rarity = 5, Power = new int[] { 8, 2, 8, 0xA } } },
            { "Raubahn Aldynn", new CardStruct { Rarity = 5, Power = new int[] { 6, 2, 9, 0xA } } },
            { "Terra Branford", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 0xA, 2, 5 } } },
            { "Warrior of Light", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 2, 5, 0xA } } },
            { "Zidane Tribal", new CardStruct { Rarity = 5, Power = new int[] { 5, 0xA, 6, 8 } } },
            { "Squall Leonhart", new CardStruct { Rarity = 5, Power = new int[] { 6, 0xA, 0xA, 1 } } },
            { "Shantotto", new CardStruct { Rarity = 5, Power = new int[] { 4, 9, 7, 9 } } },
            { "Vaan", new CardStruct { Rarity = 5, Power = new int[] { 1, 7, 0xA, 9 } } },
            { "Lightning", new CardStruct { Rarity = 5, Power = new int[] { 9, 1, 7, 0xA } } },
            { "Firion", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 5, 0xA, 1 } } },
            { "Cecil Harvey", new CardStruct { Rarity = 5, Power = new int[] { 4, 0xA, 4, 0xA } } },
            { "Tidus", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 7, 1, 9 } } },
            { "Gaelicat", new CardStruct { Rarity = 1, Power = new int[] { 4, 1, 1, 7 } } },
            { "Vanu Vanu", new CardStruct { Rarity = 2, Power = new int[] { 2, 6, 4, 7 }, CardType = CardTypes.Beast } },
            { "Gnath", new CardStruct { Rarity = 2, Power = new int[] { 6, 3, 7, 3 }, CardType = CardTypes.Beast } },
            { "Yugiri Mistwalker", new CardStruct { Rarity = 2, Power = new int[] { 7, 7, 1, 3 } } },
            { "Fat Chocobo", new CardStruct { Rarity = 2, Power = new int[] { 5, 5, 5, 5 } } },
            { "Griffin", new CardStruct { Rarity = 3, Power = new int[] { 5, 1, 7, 8 } } },
            { "Tioman", new CardStruct { Rarity = 3, Power = new int[] { 1, 5, 8, 7 } } },
            { "Estinien", new CardStruct { Rarity = 3, Power = new int[] { 8, 8, 2, 3 } } },
            { "Lucia goe Junius", new CardStruct { Rarity = 3, Power = new int[] { 8, 2, 3, 8 } } },
            { "Ysayle", new CardStruct { Rarity = 3, Power = new int[] { 4, 8, 8, 1 } } },
            { "Hilda", new CardStruct { Rarity = 3, Power = new int[] { 1, 4, 8, 8 } } },
            { "Matoya", new CardStruct { Rarity = 3, Power = new int[] { 8, 3, 8, 1 } } },
            { "Count Edmont de Fortemps", new CardStruct { Rarity = 3, Power = new int[] { 1, 8, 3, 8 } } },
            { "Byblos", new CardStruct { Rarity = 3, Power = new int[] { 8, 4, 1, 7 } } },
            { "Haurchefant", new CardStruct { Rarity = 3, Power = new int[] { 7, 1, 5, 8 } } },
            { "Aymeric", new CardStruct { Rarity = 4, Power = new int[] { 1, 5, 9, 9 } } },
            { "Ravana", new CardStruct { Rarity = 4, Power = new int[] { 9, 7, 8, 1 }, CardType = CardTypes.Primal } },
            { "Bismark", new CardStruct { Rarity = 4, Power = new int[] { 1, 9, 7, 8 }, CardType = CardTypes.Primal } },
            { "Nidhogg", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 7, 3, 8 } } },
            { "Midgardsormr", new CardStruct { Rarity = 5, Power = new int[] { 3, 8, 0xA, 7 } } },
            { "Deepeye", new CardStruct { Rarity = 1, Power = new int[] { 1, 3, 7, 2 } } },
            { "Archaeornis", new CardStruct { Rarity = 2, Power = new int[] { 5, 4, 6, 5 } } },
            { "Paissa", new CardStruct { Rarity = 2, Power = new int[] { 4, 6, 3, 6 } } },
            { "Dhalmel", new CardStruct { Rarity = 2, Power = new int[] { 6, 5, 3, 5 } } },
            { "Bandersnatch", new CardStruct { Rarity = 2, Power = new int[] { 6, 6, 3, 4 } } },
            { "Crawler", new CardStruct { Rarity = 2, Power = new int[] { 7, 7, 3, 2 } } },
            { "Poroggo", new CardStruct { Rarity = 2, Power = new int[] { 6, 3, 7, 3 } } },
            { "Vedrfolnir", new CardStruct { Rarity = 3, Power = new int[] { 8, 2, 7, 4 } } },
            { "Coeurlregina", new CardStruct { Rarity = 3, Power = new int[] { 5, 5, 5, 8 } } },
            { "Progenitrix", new CardStruct { Rarity = 3, Power = new int[] { 6, 6, 3, 6 } } },
            { "Belladonna", new CardStruct { Rarity = 3, Power = new int[] { 3, 7, 3, 7 } } },
            { "Echidna", new CardStruct { Rarity = 3, Power = new int[] { 6, 4, 7, 4 } } },
            { "Pipin Tarupin", new CardStruct { Rarity = 3, Power = new int[] { 6, 5, 6, 6 } } },
            { "Julyan Manderville", new CardStruct { Rarity = 3, Power = new int[] { 6, 6, 5, 7 } } },
            { "Moglin", new CardStruct { Rarity = 3, Power = new int[] { 8, 5, 4, 5 } } },
            { "Charibert", new CardStruct { Rarity = 3, Power = new int[] { 7, 8, 4, 3 } } },
            { "Roundrox", new CardStruct { Rarity = 3, Power = new int[] { 2, 2, 8, 8 } } },
            { "Senor Sabotender", new CardStruct { Rarity = 4, Power = new int[] { 9, 5, 7, 6 } } },
            { "Regula van Hydrus", new CardStruct { Rarity = 5, Power = new int[] { 8, 8, 6, 8 }, CardType = CardTypes.Garlean } },
            { "Archbishop Thordan VII", new CardStruct { Rarity = 5, Power = new int[] { 7, 1, 0xA, 9 } } },
            { "Honoroit", new CardStruct { Rarity = 2, Power = new int[] { 7, 2, 7, 2 } } },
            { "Hoary Boulder & Coultenet", new CardStruct { Rarity = 2, Power = new int[] { 2, 7, 2, 7 }, CardType = CardTypes.Scion } },
            { "Brachiosaur", new CardStruct { Rarity = 3, Power = new int[] { 8, 4, 5, 4 } } },
            { "Darkscale", new CardStruct { Rarity = 3, Power = new int[] { 2, 8, 4, 7 } } },
            { "Fenrir", new CardStruct { Rarity = 3, Power = new int[] { 7, 3, 6, 4 } } },
            { "Kraken", new CardStruct { Rarity = 3, Power = new int[] { 3, 6, 6, 6 } } },
            { "Vicegerent to the Warden", new CardStruct { Rarity = 3, Power = new int[] { 7, 1, 7, 5 } } },
            { "Manxome Molaa Ja Ja", new CardStruct { Rarity = 3, Power = new int[] { 3, 7, 2, 8 }, CardType = CardTypes.Beast } },
            { "Ferdiad", new CardStruct { Rarity = 3, Power = new int[] { 4, 6, 8, 4 } } },
            { "Calcabrina", new CardStruct { Rarity = 3, Power = new int[] { 6, 6, 6, 3 } } },
            { "Kuribu", new CardStruct { Rarity = 3, Power = new int[] { 8, 3, 2, 7 } } },
            { "Phlegethon", new CardStruct { Rarity = 3, Power = new int[] { 1, 7, 6, 7 } } },
            { "Artoirel de Fortemps", new CardStruct { Rarity = 3, Power = new int[] { 4, 7, 3, 7 } } },
            { "Emmanellain de Fortemps", new CardStruct { Rarity = 3, Power = new int[] { 7, 4, 7, 3 } } },
            { "Xande", new CardStruct { Rarity = 4, Power = new int[] { 9, 4, 6, 7 } } },
            { "Brute Justice", new CardStruct { Rarity = 4, Power = new int[] { 7, 7, 7, 7 } } },
            { "Sephirot", new CardStruct { Rarity = 4, Power = new int[] { 6, 8, 8, 6 }, CardType = CardTypes.Primal } },
            { "F'lhaminn", new CardStruct { Rarity = 4, Power = new int[] { 9, 7, 3, 7 }, CardType = CardTypes.Scion } },
            { "Vidofnir", new CardStruct { Rarity = 4, Power = new int[] { 8, 6, 8, 6 } } },
            { "Cloud of Darkness", new CardStruct { Rarity = 5, Power = new int[] { 7, 0xA, 7, 6 } } },
            { "Lolorito Nanarito", new CardStruct { Rarity = 2, Power = new int[] { 4, 3, 7, 3 } } },
            { "Gibrillont", new CardStruct { Rarity = 2, Power = new int[] { 2, 6, 3, 6 } } },
            { "Laniaitte de Haillenarte", new CardStruct { Rarity = 2, Power = new int[] { 7, 6, 3, 3 } } },
            { "Rhoswen", new CardStruct { Rarity = 2, Power = new int[] { 5, 6, 4, 6 } } },
            { "Carvallain de Gorgagne", new CardStruct { Rarity = 2, Power = new int[] { 2, 7, 7, 2 } } },
            { "Kal Myhk", new CardStruct { Rarity = 3, Power = new int[] { 1, 8, 4, 8 } } },
            { "Waukkeon", new CardStruct { Rarity = 3, Power = new int[] { 1, 6, 7, 7 } } },
            { "Curator", new CardStruct { Rarity = 3, Power = new int[] { 4, 6, 4, 7 } } },
            { "Mistbeard", new CardStruct { Rarity = 3, Power = new int[] { 5, 6, 7, 6 } } },
            { "Unei & Doga", new CardStruct { Rarity = 4, Power = new int[] { 6, 8, 6, 8 } } },
            { "Tiamat", new CardStruct { Rarity = 4, Power = new int[] { 9, 6, 5, 6 } } },
            { "Calofisteri", new CardStruct { Rarity = 4, Power = new int[] { 5, 8, 7, 8 } } },
            { "Hraesvelgr", new CardStruct { Rarity = 5, Power = new int[] { 7, 7, 0xA, 6 } } },
            { "Apkallu", new CardStruct { Rarity = 1, Power = new int[] { 3, 4, 4, 1 } } },
            { "Colibri", new CardStruct { Rarity = 1, Power = new int[] { 6, 1, 4, 1 } } },
            { "Magitek Death Claw", new CardStruct { Rarity = 1, Power = new int[] { 4, 3, 2, 3 }, CardType = CardTypes.Garlean } },
            { "Liquid Flame", new CardStruct { Rarity = 2, Power = new int[] { 4, 3, 6, 6 } } },
            { "Lost Lamb", new CardStruct { Rarity = 2, Power = new int[] { 7, 3, 4, 5 } } },
            { "Delivery Moogle", new CardStruct { Rarity = 2, Power = new int[] { 5, 5, 6, 3 }, CardType = CardTypes.Beast } },
            { "Magitek Colossus", new CardStruct { Rarity = 2, Power = new int[] { 6, 3, 6, 3 }, CardType = CardTypes.Garlean } },
            { "Strix", new CardStruct { Rarity = 3, Power = new int[] { 5, 7, 1, 7 } } },
            { "Tozol Huatotl", new CardStruct { Rarity = 3, Power = new int[] { 7, 6, 6, 2 }, CardType = CardTypes.Beast } },
            { "Alexander Prime", new CardStruct { Rarity = 3, Power = new int[] { 7, 3, 2, 8 }, CardType = CardTypes.Primal } },
            { "Brendt, Brennan, & Bremondt", new CardStruct { Rarity = 3, Power = new int[] { 4, 7, 6, 5 } } },
            { "Heavensward Thancred", new CardStruct { Rarity = 4, Power = new int[] { 8, 1, 7, 9 }, CardType = CardTypes.Scion } },
            { "Heavensward Y'shtola", new CardStruct { Rarity = 4, Power = new int[] { 9, 9, 2, 5 }, CardType = CardTypes.Scion } },
            { "Nael van Darnus", new CardStruct { Rarity = 4, Power = new int[] { 3, 9, 3, 9 }, CardType = CardTypes.Garlean } },
            { "Sophia", new CardStruct { Rarity = 5, Power = new int[] { 0xA, 8, 5, 6 }, CardType = CardTypes.Primal } },
            { "Opo-opo", new CardStruct { Rarity = 1, Power = new int[] { 1, 4, 2, 6 } } },
            { "Adamantoise", new CardStruct { Rarity = 2, Power = new int[] { 5, 7, 4, 4 } } },
            { "Magitek Vanguard", new CardStruct { Rarity = 2, Power = new int[] { 3, 5, 4, 7 }, CardType = CardTypes.Garlean } },
            { "Magitek Gunship", new CardStruct { Rarity = 2, Power = new int[] { 3, 5, 5, 5 }, CardType = CardTypes.Garlean } },
            { "Gold Saucer Attendant", new CardStruct { Rarity = 2, Power = new int[] { 4, 7, 1, 6 } } },
            { "Lava Scorpion", new CardStruct { Rarity = 3, Power = new int[] { 3, 8, 5, 5 } } },
            { "Magitek Predator", new CardStruct { Rarity = 3, Power = new int[] { 5, 7, 4, 5 }, CardType = CardTypes.Garlean } },
            { "Magitek Sky Armor", new CardStruct { Rarity = 3, Power = new int[] { 6, 2, 6, 7 }, CardType = CardTypes.Garlean } },
            { "Griffin (character)", new CardStruct { Rarity = 3, Power = new int[] { 8, 8, 4, 1 } } },
            { "Roland", new CardStruct { Rarity = 3, Power = new int[] { 2, 7, 8, 3 } } },
            { "Diabolos Hollow", new CardStruct { Rarity = 4, Power = new int[] { 4, 4, 8, 9 } } },
            { "Armored Weapon", new CardStruct { Rarity = 4, Power = new int[] { 3, 5, 9, 7 }, CardType = CardTypes.Garlean } },
            { "Gigi", new CardStruct { Rarity = 4, Power = new int[] { 6, 8, 4, 7 } } },
            { "Zurvan", new CardStruct { Rarity = 5, Power = new int[] { 3, 7, 8, 0xA }, CardType = CardTypes.Primal } },
            { "Namazu", new CardStruct { Rarity = 1, Power = new int[] { 1, 6, 1, 5 }, CardType = CardTypes.Beast } },
            { "Kojin", new CardStruct { Rarity = 2, Power = new int[] { 4, 5, 5, 4 }, CardType = CardTypes.Beast } },
            { "Ananta", new CardStruct { Rarity = 2, Power = new int[] { 3, 7, 5, 2 }, CardType = CardTypes.Beast } },
            { "M'naago", new CardStruct { Rarity = 2, Power = new int[] { 4, 1, 4, 7 } } },
            { "Kotokaze", new CardStruct { Rarity = 2, Power = new int[] { 5, 6, 2, 6 } } },
            { "Mammoth", new CardStruct { Rarity = 3, Power = new int[] { 6, 3, 8, 3 } } },
            { "Phoebad", new CardStruct { Rarity = 3, Power = new int[] { 8, 8, 3, 1 } } },
            { "Susano", new CardStruct { Rarity = 3, Power = new int[] { 2, 8, 3, 8 }, CardType = CardTypes.Primal } },
            { "Lakshmi", new CardStruct { Rarity = 3, Power = new int[] { 3, 7, 7, 5 }, CardType = CardTypes.Primal } },
            { "Grynewaht", new CardStruct { Rarity = 3, Power = new int[] { 7, 4, 7, 4 }, CardType = CardTypes.Garlean } },
            { "Rasho", new CardStruct { Rarity = 3, Power = new int[] { 4, 7, 8, 2 } } },
            { "Cirina", new CardStruct { Rarity = 3, Power = new int[] { 3, 5, 6, 8 } } },
            { "Magnai", new CardStruct { Rarity = 3, Power = new int[] { 6, 7, 4, 4 } } },
            { "Sadu", new CardStruct { Rarity = 3, Power = new int[] { 6, 6, 7, 4 } } },
            { "Shinryu", new CardStruct { Rarity = 4, Power = new int[] { 7, 8, 8, 2 }, CardType = CardTypes.Primal } },
            { "Yotsuyu", new CardStruct { Rarity = 4, Power = new int[] { 9, 2, 8, 6 }, CardType = CardTypes.Garlean } },
            { "Krile", new CardStruct { Rarity = 4, Power = new int[] { 2, 8, 8, 7 }, CardType = CardTypes.Scion } },
            { "Lyse", new CardStruct { Rarity = 4, Power = new int[] { 6, 9, 1, 8 }, CardType = CardTypes.Scion } },
            { "Zenos yae Galvus", new CardStruct { Rarity = 5, Power = new int[] { 6, 6, 7, 0xA }, CardType = CardTypes.Garlean } },
            { "Hien", new CardStruct { Rarity = 5, Power = new int[] { 2, 0xA, 5, 0xA } } },
        };
    }
}
